import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'
import Headshot from '/public/favicon.ico'
import FullHeadshot from '/public/Matt_Full.png'
import Marvelous from '/public/Marvelous_Screenshot.png'
import Harvest from '/public/Harvest_Screenshot.png'
import Pokedex from '/public/Pokedex_Screenshot.png'
import FCOMM from '/public/FCOMM.png'
import FCOMMBands from '/public/FranklinBandsScreenshot.png'
import MattDayMusic from'/public/MattDayMusicScreenshot.png'
import * as Scroll from 'react-scroll';




let LinkScroll = Scroll.Link;


export default function Home() {
  return (
    <>
      <Head>
        <title>Matt Day's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" property="og:title" content='Matt Day | Portfolio' />
        <meta name="image" property="og:image" content="https://i.ibb.co/HPjyDwG/Portfolio-Thumbnail.png" />
        <meta name="description" property="og:description" content='Matt Day is a full-stack software engineer from Indianapolis, IN.' />
        <meta property="og:url" content='https://portfolio-mattday92.vercel.app/' />
        <meta property="og:type" content='website' />
        <link rel="icon" href="/Matt_Full.png" />

      </Head>
      <nav class="navbar  navbar-expand-sm position-relative">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse row text-center" id="navbarNav">
            <div class="navbar-nav">
              <LinkScroll to="hero" spy={true} smooth={true} duration={500} className="nav-link col-3" >Matt Day</LinkScroll >
              <LinkScroll to="about" spy={true} smooth={true} duration={500} className="nav-link col-3" >About</LinkScroll >
              <LinkScroll to="projects" spy={true} smooth={true} duration={500} className="nav-link col-3" >Projects</LinkScroll >
              <Link href={'https://docs.google.com/document/d/1wMqOaM-pxqhQrAf2xpEux0f_B6vIxfsEG5CI_WOUNtE/edit?usp=sharing'} target='_blank' className="nav-link col-3" >Resume</Link >
            </div>
          </div>
        </div>
      </nav>
      <header className='d-flex justify-content-center'>
        <div id='hero' className='row col-10 hero'>
          <div className='col text-center'>
            <h1 className='header'>Matt Day</h1>
            <div className='social-icons my-3'>
              <Link className='social-icon' href='https://www.linkedin.com/in/mattday92' target='_blank'><i className="fa-brands fa-linkedin mx-5"></i></Link>
              <Link className='social-icon' href='https://www.github.com/mattday92' target='_blank'><i className="fa-brands fa-github mx-5"></i></Link>
            </div>
            <h2 className='my-3 subheader'>Full-Stack Software Developer</h2>
          </div>
          <div className='d-flex justify-content-center col'>
            <Image className='hero-image' src={FullHeadshot} alt="Picture of Matt Day" />
          </div>
        </div>
        <div className='big-hero-1'>
          <h1 className='big-hero-text'>Matt Day</h1>
        </div>
        <div className='big-hero-2'>
          <h1 className='big-hero-text'>Full-Stack Software Developer</h1>
        </div>
      </header>
      <div id='about' className='about d-flex justify-content-center col-12'>
        <div className='row col-10 text-center'>
          <div className='col-md-6 d-flex align-items-center justify-content-center'>
            <Image className='about-image' src={Headshot} />
          </div>
          <div className='col-md-6 about-text'>
            <h1 className='header'>About Me</h1>
            <p className='plain-text my-2'>I am a hard-working, diligent, fast-learning, and patient software engineer, proficient in Python and Javascript,
              with a Bachelor’s of Science degree in Mathematics Education from Indiana University.  In my free time, I enjoy exploring
              the performing arts as a professional guitarist and musical theatre writer.  This has helped me to develop my skills as a creative problem solver, collaborative team member,
              and independent thinker.</p>
            <div className='d-flex justify-content-around my-2'>
              <i class="fa-brands fa-html5"></i>
              <i class="fa-brands fa-css3-alt"></i>
              <i class="fa-brands fa-square-js"></i>
              <i class="fa-brands fa-python"></i>
              <i class="fa-brands fa-bootstrap"></i>
              <i class="fa-brands fa-react"></i>
              <i class="fa-solid fa-flask"></i>
              <i class="fa-brands fa-google"></i>
            </div>

          </div>
        </div>
      </div>
      <div id='projects' className='projects d-flex justify-content-center col-12'>
        <div className='row col-10 text-center d-flex justify-content-center'>
          <h1 className='header'>Projects</h1>
          <div className='row d-flex justify-content-around'>
            <div className="card my-5 px-0" >
              <Image src={Marvelous} className="card-img-top" alt="Marvelous Screenshot" />
              <div className="card-body p-0">
                <Link href={'https://marvelous-91080.web.app/'} target='_blank' ><h2 className="card-title my-2">Marvelous</h2></Link>
                <p className="card-text mx-2">Marvelous allows users to search and track information about Marvel Comics, share their thoughts on individual issues, and keep a list of their favorite books.</p>
                <div class="accordion accordion-flush" id="accordionExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        More Information
                      </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                      <div class="accordion-body">
                        Frontend UI:  React with Bootstrap and Material UI components<br /> Backend: Flask<br />Authentication using Firebase <br />User info stored using PostgreSQL <br /> <a className='btn my-3 repo-link' href='https://github.com/MattDay92/Marvelous' target='_blank'>Github Repo</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="card my-5 px-0" >
              <Image src={Harvest} className="card-img-top" alt="Harvest Tracker Screenshot" />
              <div className="card-body p-0">
                <Link href={'https://harvest-tracker-cf6d9.web.app/'} target='_blank' ><h2 className="card-title my-2">Happy Harvest Tracker</h2></Link>
                <p className="card-text mx-2">Hey, amateur gardener! Track the daily quantity and quality of all of your harvested vegetables with the Happy Harvest Tracker! </p>
                <div className='card-links'>
                  <div class="accordion accordion-flush" id="accordionExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                          More Information
                        </button>
                      </h2>
                      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                          Frontend UI:  React.js with Bootstrap and Material UI components<br /> Authentication using Firebase <br />User info stored using the Firebase NoSQL Realtime Database <br />Images obtained using the Unsplash API <br /> <a className='btn my-3 repo-link' href='https://github.com/MattDay92/HarvestTracker' target='_blank'>Github Repo</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="card my-5 px-0" >
              <Image src={FCOMM} className="card-img-top" alt="Pokedex Screenshot" />
              <div className="card-body p-0">
                <Link href={'https://www.fchschoirs.com/'} target='_blank' ><h2 className="card-title my-2">FCOMM Choirs</h2></Link>
                <p className="card-text mx-2">Informational website for the Franklin Community High School choir program in Franklin, IN.  </p>
                <div className='card-links'>
                  <div class="accordion accordion-flush" id="accordionExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                          More Information
                        </button>
                      </h2>
                      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                          Frontend UI:  React with Bootstrap Components<br /> Vanilla JS to change header images <br /> Vanilla CSS to scroll through sponsor information  <a className='btn my-3 repo-link' href='https://github.com/MattDay92/FCHSChoirs' target='_blank'>Github Repo</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="card my-5 px-0" >
              <Image src={FCOMMBands} className="card-img-top" alt="Franklin Bands Screenshot" />
              <div className="card-body p-0">
                <Link href={'https://www.franklinbands.org/'} target='_blank' ><h2 className="card-title my-2">Franklin Bands</h2></Link>
                <p className="card-text mx-2">Website for the Franklin Community High School band and guard program in Franklin, IN.  </p>
                <div className='card-links'>
                  <div class="accordion accordion-flush" id="accordionExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="headingFour">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseThree">
                          More Information
                        </button>
                      </h2>
                      <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                          Frontend UI:  React with Bootstrap Components<br /> Vanilla JS to add grow and shading effects to 'Equipment Sales' page <br /> Vanilla CSS to scroll through sponsor information  <a className='btn my-3 repo-link' href='https://github.com/MattDay92/fchs-bands' target='_blank'>Github Repo</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* <div className="card my-5 px-0" >
              <Image src={MattDayMusic} className="card-img-top" alt="mattdaymusic.net screenshot" />
              <div className="card-body p-0">
                <Link href={'https://mattdaymusic.net/'} target='_blank' ><h2 className="card-title my-2">Personal Music Website</h2></Link>
                <p className="card-text mx-2">Personal website for my other life as a musical theater composer!  </p>
                <div className='card-links'>
                  <div class="accordion accordion-flush" id="accordionExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="headingFive">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseThree">
                          More Information
                        </button>
                      </h2>
                      <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                          Frontend UI:  React with Bootstrap Components<br /> <a className='btn my-3 repo-link' href='https://github.com/MattDay92/mattdaymusic' target='_blank'>Github Repo</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> */}
          </div>
        </div>
      </div>
    </>
  )
}
