import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'
import Headshot from '/public/Matt_Day_Headshot.jpg'
import FullHeadshot from '/public/Matt_Full.png'
import Marvelous from '/public/Marvelous_Screenshot.png'
import Weather from '/public/Weather_Screenshot.png'
import Pokedex from '/public/Pokedex_Screenshot.png'
import * as Scroll from 'react-scroll';

let LinkScroll = Scroll.Link;


export default function Home() {
  return (
    <>
      <Head>
        <title>Matt Day's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <nav class="navbar navbar-expand-sm bg-dark position-relative">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse row text-center" id="navbarNav">
            <div class="navbar-nav">
              <LinkScroll to="hero" spy={true} smooth={true} offset={50} duration={500} className="nav-link col-3" >Matt Day</LinkScroll >
              <LinkScroll to="about" spy={true} smooth={true} offset={50} duration={500} className="nav-link col-3" >About</LinkScroll >
              <LinkScroll to="projects" spy={true} smooth={true} offset={50} duration={500} className="nav-link col-3" >Projects</LinkScroll >
              <Link href={'https://drive.google.com/file/d/1H3TVOKOALIKDIbP8N-JXbNCdKYSXRhMC/view?usp=sharing'} target='_blank' spy={true} smooth={true} offset={50} duration={500} className="nav-link col-3" >Resume</Link >
            </div>
          </div>
        </div>
      </nav>
      <header className='d-flex justify-content-center'>
        <div id='hero' className='row col-10 hero mb-5'>
          <div className='col-md-6 col text-center'>
            <h1 className='header'>Matt Day</h1>
            <div className='social-icons my-3'>
              <Link href='https://www.linkedin.com/in/mattday92' target='_blank'><i className="fa-brands fa-linkedin mx-5"></i></Link>
              <Link href='https://www.github.com/mattday92' target='_blank'><i className="fa-brands fa-github mx-5"></i></Link>
            </div>
            <h2 className='my-3 subheader'>Full-Stack Software Developer</h2>
          </div>
          <div className='d-flex justify-content-center col-md-6'>
            <Image className='hero-image' src={FullHeadshot} alt="Picture of Matt Day" />
          </div>
        </div>
      </header>
      <div id='about' className='about d-flex justify-content-center col-12'>
        <div className='row col-10 text-center'>
          <div className='col-md-6 d-flex align-items-center justify-content-center'>
            <Image className='about-image' src={Headshot} />
          </div>
          <div className='col-md-6 about-text'>
            <h1 className='header'>About Me</h1>
            <p className='plain-text my-2'>I am a hard-working, diligent, fast-learning, and patient software engineer, proficient in Python and Javascript,
              with a Bachelor’s of Science degree in Mathematics Education from Indiana University.  In my free time, I enjoy exploring
              the performing arts.  This has helped me to develop my skills as a creative problem solver, collaborative team member,
              and independent thinker.</p>
            <div className='d-flex justify-content-around my-2'>
              <i class="fa-brands fa-html5"></i>
              <i class="fa-brands fa-css3-alt"></i>
              <i class="fa-brands fa-square-js"></i>
              <i class="fa-brands fa-python"></i>
              <i class="fa-brands fa-bootstrap"></i>
              <i class="fa-brands fa-react"></i>
              <i class="fa-solid fa-flask"></i>
              <i class="fa-brands fa-google"></i>
            </div>

          </div>
        </div>
      </div>
      <div id='projects' className='projects d-flex justify-content-center col-12'>
        <div className='row col-10 text-center d-flex justify-content-center'>
          <h1 className='header'>Projects</h1>
          <div className='row d-flex justify-content-around'>
            <div className="card my-5" >
              <Image src={Marvelous} className="card-img-top" alt="..." />
              <div className="card-body">
                <h2 className="card-title">Marvelous</h2>
                <p className="card-text">Marvelous that allows users to search and track information about Marvel Comics, share their thoughts on individual issues, and keep a list of their favorite books.</p>
                <Link href={'https://marvelous-91080.web.app/'} target='_blank' className='btn'>More Information</Link>
              </div>
            </div>
            <div className="card my-5" >
              <Image src={Pokedex} className="card-img-top" alt="..." />
              <div className="card-body">
                <h2 className="card-title">Pokedex</h2>
                <p className="card-text">Become a Pokemon master by learning about over 1500 different Pokemon.  Create your team and battle your friends!</p>
                <Link href={'https://platinum-phrygian-stocking.glitch.me/'} target='_blank' className='btn'>More Information</Link>
              </div>
            </div>
            <div className="card my-5">
              <Image src={Weather} className="card-img-top" alt="..." />
              <div className="card-body">
                <h2 className="card-title">Weather App</h2>
                <p className="card-text">View today's weather for your location or anywhere else in the world!  </p>
                <Link href={'https://weather-a4f7b.web.app/'} target='_blank' className='btn'>More Information</Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
